ALTER TABLE racers ADD COLUMN pwd VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE racers ADD COLUMN name VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE racers ADD COLUMN account_type VARCHAR(20) NOT NULL DEFAULT 'racer';
ALTER TABLE racers ADD COLUMN initials VARCHAR(4);
ALTER TABLE racers ADD COLUMN created_at TIMESTAMP;
ALTER TABLE racers ADD CONSTRAINT racers_phone_unique UNIQUE (phone);